### PR TITLE
fix: make isBooleanLiteralType a type guard

### LINKED ISSUE #80: 🚀 Feature: make `isBooleanLiteralType` a type guard
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/ts-api-utils/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Like `isBigIntLiteralType`, `isNumberLiteralType` and `isStringLiteralType`.

### Additional Info

We can't just extend the `LiteralType` type as it explicitly declares that `value` is `string | number | PseudoBigInt`.

### PR DESCRIPTION
**Pull request by RebeccaStevens**
## PR Checklist

- [x] Addresses an existing open issue: fixes #80
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/ts-api-utils/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/ts-api-utils/blob/main/.github/CONTRIBUTING.md) were taken

### CODE REVIEW

File: src/types/typeGuards/compound.ts [hunk 1]
```diff
@@ -1,7 +1,104 @@
...
 
+import { isTypeFlagSet } from "../../flags.js";
 import { isTupleType, isTypeReference } from "./objects.js";
 
+/**
+ * `LiteralType` from typescript except that it allows for it to work on arbitrary types.
+ *
+ * @category Type Types
+ */
+export interface GeneralLiteralType extends ts.Type {
```
Comment (RebeccaStevens) [inline src/types/typeGuards/compound.ts:11]: Unfortunately, we can't just extend `ts.LiteralType`.

File: src/types/typeGuards/compound.ts [hunk 2]
```diff
@@ -1,7 +1,104 @@
...
+				(literal ? "true" : "false"))
+	);
+}
+
+/**
+ * Determines whether the given type is a boolean literal type for "true".
+ *
+ * @category Types - Utilities
+ */
+export function isTrueLiteralType(type: ts.Type): type is TrueLiteralType {
```
Comment (RebeccaStevens) [inline src/types/typeGuards/compound.ts:89]: Do we want this function (and the one below) or do we just want the overloads of `isBooleanLiteralType`.

File: src/types/typeGuards/compound.ts [hunk 3]
```diff
@@ -1,7 +1,116 @@
...
+/**
+ * Test if a type is a {@link UnknownLiteralType}?
+ *
+ * @param type
+ * @returns
+ */
+export function isUnknownLiteralType(
+	type: ts.Type
+): type is UnknownLiteralType {
+	return isTypeFlagSet(type, ts.TypeFlags.Literal);
```
Comment (RebeccaStevens) [inline src/types/typeGuards/compound.ts:54]: This function's implementation is current identical to `isLiteralType`.

File: src/types/typeGuards/compound.ts [hunk 4]
```diff
@@ -1,7 +1,116 @@
...
 
+import { isTypeFlagSet } from "../../flags.js";
 import { isTupleType, isTypeReference } from "./objects.js";
 
+/**
+ * `LiteralType` from typescript except that it allows for it to work on arbitrary types.
+ *
+ * @category Type Types
+ */
+export interface UnknownLiteralType extends ts.Type {
```
Comment (JoshuaKGoldberg) [inline src/types/typeGuards/compound.ts:11]: The naming here confused me at first a bit because _"unknown"_ normally refers to the `unknown` keyword. Is there something else we can call it?

...I can't think of anything better, and I guess it makes sense as-is. 🤷

File: src/types/typeGuards/compound.ts (hunk 2 above)
Comment (JoshuaKGoldberg) [reply src/types/typeGuards/compound.ts:101]: I see no strong reason to keep the extra functions when `isBooleanLiteralType` works for the same purposes. Let's delete. 🔪

**Review by JoshuaKGoldberg — APPROVED** [review]
👍 great!

File: src/types/typeGuards/compound.ts (hunk 4 above)
Comment (RebeccaStevens) [reply src/types/typeGuards/compound.ts:11]: I has it as "general" at first but wasn't like that name.
I decided on "unknown" because `value`'s type is `unknown`.

File: src/types/typeGuards/compound.ts (hunk 2 above)
Comment (RebeccaStevens) [reply src/types/typeGuards/compound.ts:101]: We could alternatively remove the `literal` parameter from `isBooleanLiteralType` (and the overloads).

Comment (JoshuaKGoldberg) [reply src/types/typeGuards/compound.ts:101]: 🤷 no strong preference from me, up to you!

**Comment by RebeccaStevens** [comment]
Waiting on #84

**Comment by JoshuaKGoldberg** [comment]
:shipit:
