### PR TITLE
fix: default to first declaration for getWellKnownSymbolPropertyOfType properties

### LINKED ISSUE #15: 🐛 Bug: getWellKnownSymbolPropertyOfType crashes on a property with no valueDeclaration
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/ts-api-tools/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

`getWellKnownSymbolPropertyOfType` shouldn't crash when given a `type` that has unexpected properties.

### Actual

https://github.com/typescript-eslint/typescript-eslint/issues/5458 demonstrates it crashing with:

```plaintext
    TypeError: Cannot read properties of undefined (reading 'name')
    Occurred while linting /Users/josh/repos/typescript-eslint/packages/eslint-plugin/tests/fixtures/file.ts:9
    Rule: "require-await"

      120 |       const typesToCheck = expandUnionOrIntersectionType(type);
      121 |       for (const type of typesToCheck) {
    > 122 |         const asyncIterator = tools.getWellKnownSymbolPropertyOfType(
          |                                     ^
      123 |           type,
      124 |           'asyncIterator',
      125 |           checker,

      at Object.getWellKnownSymbolPropertyOfType (../../node_modules/ts-api-tools/lib/index.cjs:377:31)
```

### Additional Info

Reproduction steps:

1. Clone https://github.com/typescript-eslint/typescript-eslint locally
2. Switch to its `v6` branch and run `yarn`
3. Add that test case to `require-await.test.ts`
4. Run `yarn jest require-await` in `packages/eslint-plugin`

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## PR Checklist

- [x] Addresses an existing open issue: fixes #15
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/ts-api-tools/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/ts-api-tools/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

If `prop.valueDeclaration` doesn't exist, then we assume `prop.getDeclarations()` must have at least one entry (_something_ must have indicated the property exists!)_.

I don't know that this assumption is actually 100% correct. But it's at least more correct than how the code was before.

### CODE REVIEW

File: src/test/utils.ts [hunk 1]
```diff
@@ -29,7 +29,7 @@ export function createSourceFileAndTypeChecker(
 	sourceText: string,
 	fileName = "file.ts"
 ): SourceFileAndTypeChecker {
-	const compilerOptions = {};
+	const compilerOptions = { target: ts.ScriptTarget.ES2018 };
```
Comment (JoshuaKGoldberg) [inline src/test/utils.ts:32]: An ES2018 script target allows `Symbol` to exist.

File: src/types/getters.ts [hunk 2]
```diff
@@ -52,12 +52,12 @@ export function getWellKnownSymbolPropertyOfType(
...
 
+		const declaration = prop.valueDeclaration ?? prop.getDeclarations()![0];
+
 		const globalSymbol = typeChecker.getApparentType(
 			typeChecker.getTypeAtLocation(
-				(
-					(prop.valueDeclaration as ts.NamedDeclaration)
-						.name as ts.ComputedPropertyName
-				).expression
+				((declaration as ts.NamedDeclaration).name as ts.ComputedPropertyName)
```
Comment (RebeccaStevens) [inline src/types/getters.ts:59]: Do we know for sure that `declaration` is always a `NamedDeclaration` and it's name is always a `ComputedPropertyName`?

If not, we should probably add this above:

```ts
if (!isNamedDeclaration(declaration) || declaration.name === undefined || !ts.isComputedPropertyName(declaration.name)) {
	continue;
}
```

`isNamedDeclaration` doesn't currently exists though. We should create it.

Comment (RebeccaStevens) [inline src/types/getters.ts:59]: Do we know for sure that `declaration` is always a `NamedDeclaration` and it's name is always a `ComputedPropertyName`?

If not, we should probably add this above:

```ts
if (!isNamedDeclaration(declaration) || declaration.name === undefined || !ts.isComputedPropertyName(declaration.name)) {
	continue;
}
```

`isNamedDeclaration` doesn't currently exists though. We should create it.

**Review by RebeccaStevens — CHANGES_REQUESTED** [review]
I don't like the look of those casts.
Do we know for sure that those values are always those types?

File: src/nodes/typeGuards/compound.ts [hunk 3]
```diff
@@ -61,6 +61,12 @@ export function isJsxTagNamePropertyAccess(
 	);
 }
 
+export function isNamedDeclaration(
+	node: ts.Declaration
+): node is ts.NamedDeclaration {
+	return "name" in node;
+}
```
Comment (JoshuaKGoldberg) [inline src/nodes/typeGuards/compound.ts:68]: 🤔 I'm not 100% that this is right... but couldn't think of anything better given how small the `ts.NamedDeclaration` type is:

```ts
export interface NamedDeclaration extends Declaration {
    readonly name?: DeclarationName;
}
```

File: src/types/getters.ts (hunk 2 above)
Comment (JoshuaKGoldberg) [reply src/types/getters.ts]: Good point!

File: src/nodes/typeGuards/compound.ts (hunk 3 above)
Comment (RebeccaStevens) [reply src/nodes/typeGuards/compound.ts:68]: Probably best to add an `&& isDeclarationName(node.name)`

Comment (JoshuaKGoldberg) [reply src/nodes/typeGuards/compound.ts:68]: Ah good point. `node.name` is optional, so I guess this is needed only if it exists?

**Comment by JoshuaKGoldberg** [comment]
> will re-request

...which I can't do now. The GitHub requests edge cases always confuse me.

File: src/nodes/typeGuards/compound.ts (hunk 3 above)
Comment (RebeccaStevens) [reply src/nodes/typeGuards/compound.ts:72]: Actually, it being optional is a bit confusing. Surely if it doesn't have a name it isn't a named declaration.

I think for now it might be best to just go with:

 ```ts
const isNamedDeclaration = isDeclaration as (node: TS.Node) => node is ts NamedDeclaration
```

Seems the name prop doesn't need to exist at all.

Comment (JoshuaKGoldberg) [reply src/nodes/typeGuards/compound.ts:72]: Yeah I'll just go with the latter for now.

**Review by RebeccaStevens — APPROVED** [review]

File: src/types/getters.ts (hunk 2 above)
Comment (RebeccaStevens) [reply src/types/getters.ts]: After some research, I made a new PR (#66) that address this type guard.

File: src/nodes/typeGuards/compound.ts [hunk 4]
```diff
@@ -61,6 +61,16 @@ export function isJsxTagNamePropertyAccess(
...
 
+/**
+ * @remarks This always returns true.
+ * @see https://github.com/JoshuaKGoldberg/ts-api-utils/pull/16#discussion_r1106579774
+ */
+export function isNamedDeclaration(
+	node: ts.Declaration
+): node is ts.NamedDeclaration {
+	return true;
+}
```
Comment (JoshuaKGoldberg) [inline src/nodes/typeGuards/compound.ts:72]: @RebeccaStevens I'm up for waiting till #66 is merged before taking in that change here. Up to you?
