### PR TITLE
fix: account for mapped types without modifiers in isPropertyReadonlyInType

### LINKED ISSUE #17: 🐛 Bug: isPropertyReadonlyInType crashes on a mapped type parameter extending any
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/ts-api-tools/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

`isPropertyReadonlyInType` shouldn't crash if provided a `type` that doesn't have a `modifiersType` property. Per https://github.com/ajafff/tsutils/pull/136#issue-904052400 that's actually possible.

```ts
type MyType<T> = {
  [K in keyof T]: 'cat' | 'dog' | T[K];
};

function method<A extends any[] = string[]>(value: MyType<A>) {
  return value;
}
```

### Actual

Per https://github.com/typescript-eslint/typescript-eslint/issues/3405:

```plaintext
TypeError: Cannot read properties of undefined (reading 'flags')
 ❯ Module.isUnionType src/types/typeGuards.ts:39:15
     37| 
     38| export function isUnionType(type: ts.Type): type is ts.UnionType {
     39|  return (type.flags & ts.TypeFlags.Union) !== 0;
       |               ^
     40| }
     41| 
 ❯ unionTypeParts src/types/utilities.ts:243:9
 ❯ isPropertyReadonlyInType src/types/utilities.ts:132:24
 ❯ isReadonlyPropertyFromMappedType src/types/utilities.ts:98:32
 ❯ src/types/utilities.ts:61:12
 ❯ someTypePart src/types/utilities.ts:218:55
 ❯ isReadonlyPropertyIntersection src/types/utilities.ts:52:9
 ❯ Module.isPropertyReadonlyInType src/types/utilities.ts:146:4
```

### Additional Info

Reproduction steps:

1. Clone https://github.com/typescript-eslint/typescript-eslint locally
2. Switch to its `v6` branch and run `yarn`
3. Add that test case to `prefer-readonly-parameter-types.test.ts`
4. Run `yarn jest require-await` in `packages/eslint-plugin`

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## PR Checklist

- [x] Addresses an existing open issue: fixes #17
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/ts-api-tools/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/ts-api-tools/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Checks if `type.modifiersType` exists before asking `isPropertyReadonlyInType(modifiersType, ...)`.

This is a recreation of https://github.com/ajafff/tsutils/pull/136. Which means 😄:

Co-authored-by: @kirjs

### CODE REVIEW

File: src/types/utilities.ts [hunk 1]
```diff
@@ -92,10 +92,11 @@ function isReadonlyPropertyFromMappedType(
 		!/^__@[^@]+$/.test(name as string)
 	)
 		return declaration.readonlyToken.kind !== ts.SyntaxKind.MinusToken;
-	return isPropertyReadonlyInType(
-		(type as unknown as { modifiersType: ts.Type }).modifiersType,
-		name,
-		typeChecker
+
+	const { modifiersType } = type as { modifiersType?: ts.Type };
```
Comment (RebeccaStevens) [inline src/types/utilities.ts:96]: We might want to create a `hasModifiersType` utility function.
Lets do this in another PR though.

**Review by RebeccaStevens — APPROVED** [review]

**Comment by JoshuaKGoldberg** [comment]
@allcontributors add @JoshuaKGoldberg for bug
