### PR TITLE
fix: make `isFalsyType()` return `true` for `0n`

### LINKED ISSUE #544: 🐛 Bug: isFalsyType should return true for `0n`
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/ts-api-utils/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

given the literal `0n` type, `isFalsyType(type)` should be true.

### Actual

`isFalsyType(type)` is false.

### Additional Info

This is because the ts api returns a `PseudoBigInt` object (rather than a `bigint` primitive) which is always truthy, causing this check to be incorrect:

https://github.com/JoshuaKGoldberg/ts-api-utils/blob/41cd21d41f445448681dd32308a48a004f4717cb/src/types/utilities.ts#L49-L51

See also https://github.com/typescript-eslint/typescript-eslint/pull/10205/files

### PR DESCRIPTION
**Pull request by kirkwaiblinger**
## PR Checklist

- [x] Addresses an existing open issue: fixes #544 
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/ts-api-utils/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/ts-api-utils/blob/main/.github/CONTRIBUTING.md) were taken

## Overview
The `type.value` returns a `PseudoBigInt` object rather than an actual bigint for TS legacy support reasons. Therefore, to determine if a literal is a falsy value, we cannot rely on the truthiness of `type.value` alone, and need to check what the actual object is if it's not a primitive.

### CODE REVIEW

File: src/types/utilities.ts [hunk 1]
```diff
@@ -47,7 +47,11 @@ export function isFalsyType(type: ts.Type): boolean {
 	}
 
 	if (type.isLiteral()) {
-		return !type.value;
+		if (typeof type.value === "object") {
+			return type.value.base10Value === "0";
```
Comment (kirkwaiblinger) [inline src/types/utilities.ts:51]: Would also be completely possible to do convert to an actual bigint, i.e.
`return !BigInt((type.value.negative ?  "-" : "") + type.value.base10Value)`.
However, we don't actually need the bigint value here, so 🤷

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Unit tests are failing, could you fix those up please?

File: src/types/utilities.ts (hunk 1 above)
Comment (JoshuaKGoldberg) [reply src/types/utilities.ts:51]: Yeah 🤷 I'm more motivated to keep this simple than anything else.

**Comment by RebeccaStevens** [comment]
Looks like the issue is caused by an update to pnpm, to a version not compatible with the version of node we're using for the testing. #531 should fix this.

**Comment by kirkwaiblinger** [comment]
> Looks like the issue is caused by an update to pnpm, to a version not compatible with the version of node we're using for the testing. #531 should fix this.

I'm thinking it's best if I just wait with this PR until that gets merged then?

**Comment by JoshuaKGoldberg** [comment]
Oh, I was looking at TypeScript 4.9.5 on https://github.com/JoshuaKGoldberg/ts-api-utils/actions/runs/11544117529/job/32131517301?pr=545:

```plaintext
 FAIL  src/types/utilities.test.ts > isFalsyType > returns true when given 0n
 FAIL  src/types/utilities.test.ts > isFalsyType > returns true when given -0n
AssertionError: expected false to be true // Object.is equality
```

#531 will drop support for TS <4.8, but I reproduce this issue on TS 4.8 and 4.9 locally.

**Comment by kirkwaiblinger** [comment]
i'll take a look then! 👍

**Comment by JoshuaKGoldberg** [comment]
@all-contributors please add @kirkwaiblinger for code.

> 🤖 Beep boop! This comment was added automatically by [all-contributors-auto-action](https://github.com/marketplace/actions/all-contributors-auto-action).
> Not all contributions can be detected from Git & GitHub alone. Please comment any missing contribution types this bot missed.
> ...and of course, thank you for contributing! 💙
